language: python
python:
  - 2.7
  - 3.5
notifications:
  email: false

# turn on container support
sudo: false 

# Setup anaconda
# This is specifically for scientific python support in travis and comes from
# https://gist.github.com/dan-blanchard/7045057
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy nose pandas
  - python setup.py install --user

# Run test
script:
  - nosetests -w tests
